credentials:
  usernames:
    admin_user:
      name: Admin
      password: '$2b$12$KIXfQXq2Ihz2fTfQzya4VOGUErFei/mZ4eZPKP6zTyMuFkeVO/Sm6'  # password: admin123
      email: admin@example.com
    analyst_user:
      name: Analyst
      password: '$2b$12$Wb5P6xP.HHRR2j5CrKyt7OFNHiOwFX7Ljkmu.y3yU2LuJpxdHITbK'  # password: analyst123
      email: analyst@example.com

cookie:
  name: smartshield_cookie
  key: some_signature_key
  expiry_days: 3

preauthorized:
  emails:
    - admin@example.com
    - analyst@example.com
